# Generated by Django 5.2.6 on 2025-10-22 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
        ('receptionist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='Patient_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='receptionist',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Appointment_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='admin_app.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.CreateModel(
            name='Bill_Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_fee', models.DecimalField(decimal_places=2, default=250, max_digits=10)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Billing_date', models.DateField(auto_now_add=True)),
                ('Token', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('Appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='receptionist_app.appointment')),
                ('Patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='receptionist_app.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='receptionist_app.patient'),
        ),
    ]
