# Generated by Django 5.2.6 on 2025-10-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Receptionist', 'Receptionist'), ('Doctor', 'Doctor'), ('Pharmacist', 'Pharmacist'), ('Lab_Technician', 'Lab Technician')], max_length=20),
        ),
    ]
