# Generated by Django 5.2.6 on 2025-10-23 06:05

import django.db.models.deletion
import doctor_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        ('receptionist_app', '0002_rename_first_name_patient_patient_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultationid', models.AutoField(primary_key=True, serialize=False)),
                ('consultationdate', models.DateField(default=doctor_app.models.get_today_date)),
                ('consultationtime', models.TimeField(default=doctor_app.models.get_current_time)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('INPROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('consultation_notes', models.TextField(blank=True, null=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='receptionist_app.appointment')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='admin_app.staff')),
            ],
            options={
                'db_table': 'doctor_app_consultations',
                'ordering': ['-consultationdate'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescriptionid', models.AutoField(primary_key=True, serialize=False)),
                ('prescriptiondate', models.DateField(default=doctor_app.models.get_today_date)),
                ('general_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctor_app.consultation')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='admin_app.staff')),
            ],
            options={
                'db_table': 'doctor_app_prescription',
                'ordering': ['-prescriptiondate'],
            },
        ),
        migrations.CreateModel(
            name='MedicinePrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinename', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('timing', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_prescriptions', to='doctor_app.prescription')),
            ],
            options={
                'db_table': 'doctor_app_medicineprescriptions',
            },
        ),
        migrations.CreateModel(
            name='TestPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_prescriptions', to='doctor_app.prescription')),
            ],
            options={
                'db_table': 'doctor_app_testprescriptions',
            },
        ),
    ]
