# Generated by Django 5.2.6 on 2025-10-21 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        ('receptionist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('low_range', models.DecimalField(decimal_places=2, help_text='Normal range lower limit', max_digits=10)),
                ('high_range', models.DecimalField(decimal_places=2, help_text='Normal range upper limit', max_digits=10)),
                ('unit', models.CharField(help_text='e.g., mg/dL, %, count/mm3', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['test_name'],
            },
        ),
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ordered', 'Ordered'), ('Sample Collected', 'Sample Collected'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Ordered', max_length=20)),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('STAT', 'STAT')], default='Normal', max_length=20)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('sample_collection_date', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_orders', to='receptionist_app.appointment')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_technician_app.labtest')),
                ('ordered_by', models.ForeignKey(help_text='Doctor/Staff who ordered the test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_tests', to='admin_app.staff')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptionist_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_normal', models.BooleanField(default=True, help_text='Is result within normal range?')),
                ('technician_notes', models.TextField(blank=True)),
                ('result_date', models.DateTimeField(auto_now_add=True)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(help_text='Lab technician who performed the test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_tests', to='admin_app.staff')),
                ('test_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='lab_technician_app.testorder')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Senior technician/doctor who verified results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tests', to='admin_app.staff')),
            ],
        ),
    ]
